AssignmentManager/AssignmentManager/Entities/Assignment.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace AssignmentManager.Entities
{
    public class Assignment : BaseEntity
    {
        [Required]
        public string Title { get; set; }
        public string Description { get; set; }
        public bool IsDone { get; set; }

        public virtual List<Comment> Comments{ get; set; }
    }
}

AssignmentManager/AssignmentManager/Entities/BaseEntity.cs
using System;

namespace AssignmentManager.Entities
{
    public abstract class BaseEntity
    {
        public int Id { get; set; }
        public DateTime CreatedAt { get; set; }
        public DateTime UpdatedAt { get; set; }
    }
}

AssignmentManager/AssignmentManager/Entities/Comment.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AssignmentManager.Entities
{
    public class Comment : BaseEntity
    {
        public string Content { get; set; }
        public int AssignmentId { get; set; }
        public virtual Assignment Assignment { get; set; }
    }
}

AssignmentManager/AssignmentManager/Controllers/AssignmentController.cs
using AssignmentManager.DataAccess;
using AssignmentManager.Entities;
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace AssignmentManager.Controllers
{
    public class AssignmentController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.Stdroup1 = "We are awesome!";
            List<Assignment> assignments = new List<Assignment>();
            AssignmentRepository assignmentRepository = new AssignmentRepository();
            assignments.AddRange(assignmentRepository.GetAll());
            return View(assignments);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Assignment entity)
        {
            entity.CreatedAt = DateTime.Now;
            entity.UpdatedAt = DateTime.Now;
            entity.IsDone = false;

            var assignmentRepository = new AssignmentRepository();
            assignmentRepository.Insert(entity);

            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Update(int id)
        {
            var assignmentRepository = new AssignmentRepository();
            Assignment entity = assignmentRepository.GetById(id);

            return View(entity);
        }

        [HttpPost]
        public ActionResult Update(Assignment entity)
        {
            entity.UpdatedAt = DateTime.Now;

            var assignmentRepository = new AssignmentRepository();
            assignmentRepository.Update(entity);

            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            var assignmentRepository = new AssignmentRepository();
            var entity = assignmentRepository.GetById(id);
            assignmentRepository.Delete(entity);

            return RedirectToAction("Index");
        }
	}
}

AssignmentManager/AssignmentManager/Controllers/CommentController.cs
using AssignmentManager.DataAccess;
using AssignmentManager.Entities;
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace AssignmentManager.Controllers
{
    public class CommentController : Controller
    {
        public ActionResult Index(int id)
        {
            var commentsRepository = new CommentsRepository();
            var commentsList = new List<Comment>();

            var commentsFromRepository = commentsRepository
                .GetAll(comment => comment.AssignmentId == id);

            ViewBag.AssignmentId = id;

            var assignmentRepository = new AssignmentRepository();

            ViewBag.AssignmentTitle = assignmentRepository.GetById(id).Title;

            commentsList.AddRange(commentsFromRepository);

            return View(commentsList);
        }

        [HttpGet]
        public ActionResult Create(int id)
        {
            var entity = new Comment() 
            { 
                AssignmentId = id
            };
            
            return View(entity);
        }

        [HttpPost]
        public ActionResult Create(Comment entity)
        {
            entity.CreatedAt = DateTime.Now;
            entity.UpdatedAt = DateTime.Now;

            var commentsRepository = new CommentsRepository();
            commentsRepository.Insert(entity);

            return RedirectToAction("Index/" + entity.AssignmentId);
        }

        [HttpGet]
        public ActionResult Update(int id)
        {
            var commentsRepository = new CommentsRepository();
            var entity = commentsRepository.GetById(id);

            return View(entity);
        }

        [HttpPost]
        public ActionResult Update(Comment entity)
        {
            entity.UpdatedAt = DateTime.Now;

            var commentsRepository = new CommentsRepository();
            commentsRepository.Update(entity);
            
            return RedirectToAction("Index/" + entity.AssignmentId);
        }
        
        public ActionResult Delete(int id)
        {
            var commentsRepository = new CommentsRepository();
            var entity = commentsRepository.GetById(id);
            commentsRepository.Delete(entity);

            return RedirectToAction("Index/" + entity.AssignmentId);
        }
	}
}

AssignmentManager/AssignmentManager/Controllers/HomeController.cs
using System.Web.Mvc;

namespace AssignmentManager.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

AssignmentManager/AssignmentManager/Views/Assignment/Create.cshtml
@model AssignmentManager.Entities.Assignment
@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "Assignment"))
{
    <div class="container">
        <div class="form-group row">
            <div class="col-md-3">
                @Html.LabelFor(model => model.Title)
                @Html.TextBoxFor(model => model.Title, new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group row">
            <div class="col-md-3">
                @Html.LabelFor(model => model.Description)
                @Html.TextAreaFor(model => model.Description, new { @class = "form-control", @rows = "5" })
            </div>
        </div>
        <div>
            <input type="submit" value="Create" class="btn btn-success"/>
        </div>
    </div> 
}

AssignmentManager/AssignmentManager/Views/Assignment/Index.cshtml
@* ASSINGMENTS *@

@model List<AssignmentManager.Entities.Assignment>
<h1 class="pull-left">@ViewBag.Stdroup1</h1>
<a href="/Assignment/Create" class="btn btn-info pull-right" style="margin-top: 20px">Insert</a>
<table class="table table-bordered">
    <thead>
        <tr>
            <th>Title</th>
            <th>Description</th>
            <th>Created At</th>
            <th>Updated At</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var assignment in Model)
        {
            <tr>
                <td>@assignment.Title</td>
                <td>@assignment.Description</td>
                <td>@assignment.CreatedAt.ToString("dd/MM/yyyy")</td>
                <td>@assignment.UpdatedAt.ToString("dd/MM/yyyy")</td>
                <td>
                  <a href="/Assignment/Update/@assignment.Id" class="btn btn-default">Update</a>
                  <a href="/Assignment/Delete/@assignment.Id" class="btn btn-danger">Delete</a>
                  <a href="/Comment/Index/@assignment.Id" class="btn btn-info">Comments</a>
                </td>
            </tr>
        }
    </tbody>
</table>

AssignmentManager/AssignmentManager/Views/Assignment/Update.cshtml
@model AssignmentManager.Entities.Assignment
@{
    ViewBag.Title = "Update";
}

<h2>Update</h2>

@using (Html.BeginForm("Update", "Assignment"))
{
    @Html.HiddenFor(model => model.CreatedAt)
    <div class="container">
        <div class="form-group row">
            <div class="col-md-3">
                @Html.LabelFor(model => model.Title)
                @Html.TextBoxFor(model => model.Title, new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group row">
            <div class="col-md-3">
                @Html.LabelFor(model => model.Description)
                @Html.TextAreaFor(model => model.Description, new { @class = "form-control", @rows = "5" })
            </div>
        </div>
        <div class="form-group row">
            <div class="col-md-3">
                @Html.LabelFor(model => model.IsDone, "Done: ")
                @Html.CheckBoxFor(model => model.IsDone)
            </div>
        </div>
        <div>
            <input type="submit" value="Update" class="btn btn-success" />
        </div>
    </div>
}

AssignmentManager/AssignmentManager/Views/Comment/Create.cshtml
@model AssignmentManager.Entities.Comment
@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "Comment"))
{
    @Html.HiddenFor(model => model.AssignmentId)
    <div class="container">
        <div class="form-group row">
            <div class="col-md-3">
                @Html.LabelFor(model => model.Content)
                @Html.TextAreaFor(model => model.Content, new { @class = "form-control", @rows = "5" })
            </div>
        </div>
        <div>
            <input type="submit" value="Create" class="btn btn-success" />
        </div>
    </div>
}

AssignmentManager/AssignmentManager/Views/Comment/Index.cshtml
@* COMMENTS *@

@model List<AssignmentManager.Entities.Comment>
<h1 class="pull-left">Comments @ViewBag.AssignmentTitle</h1>
<a href="/Comment/Create/@ViewBag.AssignmentId" class="btn btn-success pull-right" style="margin-top: 20px">Insert</a>
<table class="table table-bordered">
    <thead>
        <tr>
            <th>Content</th>
            <th>Created At</th>
            <th>Updated At</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var comment in Model)
        {
            <tr>
                <td>@comment.Content</td>
                <td>@comment.CreatedAt.ToString("dd/MM/yyyy")</td>
                <td>@comment.UpdatedAt.ToString("dd/MM/yyyy")</td>
                <td>
                    <a href="/Comment/Update/@comment.Id" class="btn btn-default">Update</a>
                    <a href="/Comment/Delete/@comment.Id" class="btn btn-danger">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

AssignmentManager/AssignmentManager/Views/Comment/Update.cshtml
@model AssignmentManager.Entities.Comment
@{
    ViewBag.Title = "Update";
}

<h2>Update</h2>

@using (Html.BeginForm("Update", "Comment"))
{
    @Html.HiddenFor(model => model.CreatedAt)
    @Html.HiddenFor(model => model.AssignmentId)
    <div class="container">
        <div class="form-group row">
            <div class="col-md-3">
                @Html.LabelFor(model => model.Content)
                @Html.TextAreaFor(model => model.Content, new { @class = "form-control", @rows = "5" })
            </div>
        </div>
        <div>
            <input type="submit" value="Update" class="btn btn-success" />
        </div>
    </div>
}

AssignmentManager/AssignmentManager/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

AssignmentManager/AssignmentManager/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

AssignmentManager/AssignmentManager/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-large">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

AssignmentManager/AssignmentManager/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Assignments List", "Index", "Assignment")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>